name: TF-plan-DEV

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_ID}}
  APP_TAG: app-version-${{ github.sha }}

jobs:
  DOS:
    name: running terraform plan
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: terraform

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{env.AWS_SECRET_KEY}}
          aws-region: "eu-west-2"

      - name: "Use terraform 1.1.7"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: "Terraform fmt"
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: "Terraform init"
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: "Terraform plan"
        id: plan
        run: terraform plan -no-color -out plan.out
        working-directory: ${{ env.WORKING_DIRECTORY }}
